### ISSUE TITLE
Make manual delay more user-friendly

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#123]
I have a number of suggestions for making the flight computer's manual delay feature easier to use. (Disclaimer: suggestions may actually make it harder to use, more discussion/polling needed).
- It's hard to remember to hit enter for the manual delay, especially since the other text boxes in the flight computer -- the custom attitude and the burn length -- don't require hitting enter (sure, you _can_ hit enter to start a burn, but you can also click the burn button). Two possible solutions: 
  - Add a "set" button next to delay box. This would serve as a visual reminder that just typing is not enough.
  - Reparse the text box whenever it's updated. Since manual delay only takes effect when you schedule a command, this shouldn't cause problems from the delay being updated in mid-typing. I think. Probably.
- At the moment, all flight computer features, including manual delay, stay on when you close the flight computer window. Manual delay is the most problematic, since it leads to the confusing behavior that nothing happens when you try to act. Again, two options:
  - Have manual delay, and only manual delay, turn off when you close the flight computer window. This would prevent players from having to disable the delay every time, but it would cause trouble for players who like to hide the window whenever they're not setting something directly related to the computer. It would also make the computer's behavior less self-consistent, which could make it harder to understand.
  - Have everything turn off (including state/queues) when you close the flight computer. Has the advantage of self-consistency, but makes the "I like to hide the window" problem more extreme. If implemented, would make #50 obsolete.

This is a usability issue, so it should really be done in whatever makes the most sense to the most players. Thoughts?

**Comment by JDPKSP** [comment]
I'm currently playing with the extraDelay functionality a bit. I'm thinking about expanding it to a whole set of conditionals (eg.: altitude, height from terrain, speed, and so forth), so the player has more control over when a command will pop. The current behaviour is:
if the timestamp has passed and the condition is met (or there is no condition) the command will pop.
I've implemented some rudimentary Tminus estimation for conditions, for use with timewarp throttling as well.

you can take a look at my preliminary work here:
[JDPKSP/RemoteTech2/Conditionals](http://github.com/JDPKSP/RemoteTech2/tree/Conditionals)

Conditionals are mainly intended to make it easier for the player to land and take off within signal delay, so that being said some more stuff will need to be added (notably autostaging and speed controlled throttle commands). I'd like to hear your thoughts before I do any pull requests.


My intention is to change the behaviour (of mainly the UI) a bit:

**QueueFragment:**
To the immediate left of the text input field (currently referencing mExtraDelay) there will be a combobox from which you can switch condition types (defaults to: None).
text input into the input field is parsed in conjunction with the selected condition type into a condition whenever a command is enqueued  within the flight computer. Meaning that the player does not need to press enter to activate a condition. Since conditions are only pushed together with commands, it is unnecessary to have the player press a button two times in order for the flight computer to send the command they want to.

Perhaps We'd want to continually check if the string is parseable, and turn the field background red if not, alerting the user that their condition will fail (akin to what HyperEdit does).


**FlightComputer:**
Add support for rudimentary autoStaging. Where the flight computer will automatically stage if all engines in the active stage go out of resources.

Since AutoStaging is a setting within the satellite itself, reaction to the press of the toggle needs to be subject to signal delay (+ condition). Therefore a new command will be added that simply feeds a value back to the flight computer. Room for expansion with this one in case there are other fields we wish to subject to signal delay
(wouldn't it be wonderfull if someone found a way to hook into GuiActive fields, so we could close the current exploit of throttle clamping engines for instant control)

Add KeepSpeed option to burn commands. Where the flight computer assumes that you are pointing retrograde/vertical and controls the throttle to maintain a constant surface speed. This is mainly intended for landing and takeoff maneuvers.


**AttitudeFragment**
set the default throttle to 100%
Compress the textfield for time or D/V input to 1/3 width and place a combobox immediately to its right for toggling between the three modes(time, D/V or keep speed). The last 3rd of the space (right-most) is reserved for a toggle for autostaging. Pressing it will immediately queue an InternalCommand, and popping it will set the visual value of the toggle (up/down).

**Comment by neitsa** [comment]
I'm closing this issue for the following reasons:

1. The delay feature on the FC Window was implemented
2. As discussed here, #26 is a proposal we'll implement in the 2.x branch.
2. #498 is a list of features from @JDPKSP we'd like to implement (this one stays open, I'm adding a note on this issue to link to the comment)
3. We'll do a complete FC overhaul for RT 2.0 (at least from a code POV, but maybe also for the interface).
