### ISSUE TITLE
Dedicated Radio Controller/Computers

### ISSUE THREAD

**Issue by ddproxy** [RemoteTechnologiesGroup/RemoteTech#127]
Stemming from #126, I think a dedicated computer (similar to kOS's computer model) should be required for more powerful antenna and dishes as a balancing factor. The controller could be required to perform maneuvers.

With increased range comes increased issues [summarized from a comment](https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/126#issuecomment-47957087) from AdmiralTigerclaw - so would it make sense that a new unit could be used to 'virtually' filter through the signal and properly parse the connection.

Each "Radio Controller" could support a limited number of active antenna/dishes. Taking in Jyro117's [suggestion](https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/126#issuecomment-47947192) for modifying effectiveness of omni-antenna's and allowing their ranges to stack, this unit would force a limiting factor to the number of antennas per "Radio Controller" and cause the player to select the more efficient antenna for the situation as the original issue of #126

**Comment by neitsa** [comment]
We are currently reviewing old feature request with the team in preparation for the RT 2.x branch and we'll not implement this feature request "as is" (we are open to discussion of course): the whole discussion summed up pretty much why we won't implement it.

* It's too complicated, not necessarily to implement but from a player point of view
* There's a risk of imbalance if we implement it (it will require a lot of tests to get it right)
* As @AdmiralTigerclaw wrapped up it's more an antenna feature than a probe core feature

@ddproxy : if you have the will to implement it on your side, we'd happy to give you hand and / or make some adjustments so that the plugin could be easily integrated with RT. Feel free to open a new feature request if you want to rework the idea.
