### ISSUE TITLE
Remote Tech non functional when using Dark Multiplayer (DMP)

### ISSUE THREAD

**Issue by lamper** [RemoteTechnologiesGroup/RemoteTech#149]
Hi All,

Not sure if this is me or a bug....

Been playing KSP using the Dark MultiPlayer (DMP) with a couple of friends. We are trying to establish a base on Mun using MKS (http://forum.kerbalspaceprogram.com/.../threads/79588), TAC, Remote Tech 2, and Mechjeb.

Seeing some strange behaviour from Remote Tech - namely that when I launch an unmanned probe it does not require a connection to KSC and no matter where I put the craft in space - past the horizon - out of range of the antenna etc - it ALWAYS appears to be under local control. Is this a DMP known issue or something else.

I noticed this when establishing a sat network for our first survey of the Mun.  First satellite was launched and put in geo-stationary orbit, second satellite launched and when I left the LOS of KSC it should have used the first satellite to relay back, but instead it just carried on and stayed under local control - even on the far side of the planet.

Cheers

**Comment by KSP-TaxiService** [comment]
Hi,

No response was provided for 2 years and it is known that Dark MultiPlayer mod causes a number of issues due to the KSP being a single-player. This ticket will be closed due to this age.

Should this issue be still occurring in KSP 1.3 onwards, kindly file a new issue and provide the log required in order to analyse the issue.
