### ISSUE TITLE
RT windows don't block keyboard input on Linux

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#197]
Any keystrokes typed into e.g. the flight computer window also get parsed by KSP for Linux (whatever you do, *don't* hit backspace). Appears to be common to 32- and 64-bit games, and does not require any third-party mods or special circumstances to reproduce. KSP logs show no exceptions or diagnostic messages.

See forum discussion starting at http://forum.kerbalspaceprogram.com/threads/83305?p=1451609#post1451609.

**Comment by FloFri** [comment]
Just to bring this back up. I run the latest release on 0.9. Still a problem here. Bit it looks like kOS at least found a solution, because there are no problems anymore, when typing in their terminal.

**Comment by Peppie23** [comment]
@erendrake can you help here? :blush:

**Comment by Peppie23** [comment]
a wait. I thought it's issue #228 

@FloFri can you try with this dll: https://www.dropbox.com/s/f9fvhijzjf22lkx/RemoteTech_v1.6-alpha-alpha.zip?dl=0 (but not on your career saves ) ^^ and give me a feedback

**Comment by FloFri** [comment]
@Peppie23 The new dll fixes half of the problem. Modifier keys like shift and ctrl are now blocked while in the flight computer, but normal keys (for example m or x) still are not blocked.

**Comment by Peppie23** [comment]
@FloFri thanks for testing. I'll make a new version today.

**Comment by Peppie23** [comment]
@FloFri can you please use the same dll and try to keep your mouse over the window and tell me if this would work

**Comment by erendrake** [comment]
@Peppie23 this is a PITA. I was not involved with the fix for this bug but as you can see we ended up having to build a glue table to get everything mapped correctly. Moving the fix over from kOS should work for most of these jeys

**Comment by Peppie23** [comment]
https://www.dropbox.com/s/yr98097pa3xj3fd/RemoteTech_v1.6-alpha-alpha-2.zip?dl=1

ok i think i'm done with that issue. I insert a stackLock for `ControlTypes.ALL_SHIP_CONTROLS` if one remotetech input is focused.

btw: what is a PITA? :relaxed:

**Comment by erendrake** [comment]
Pain in the ass ☺

**Comment by FloFri** [comment]
@Peppie23 have tested this latest Version. But problem still exists with some keys (for example y, z and m), even when the flight computer has the focus and the mouse is in the text field. But other keys (Shift, wasg) work now, when the flight computer has the focus.

**Comment by Peppie23** [comment]
ok this is my last try otherwise i'll give up.

I found a way to simulate this problem on windows, so maybe a good sign to fix that issue already. Adding a Lock for `ALL_SHIP_CONTROLS` will only lock the ship controls like `w,a,s,d,shift etc..`, good :+1: i also tried to use the `ALL` lock but no change to the `Z` or `X` key. This is way i also changed the `OnFlyByWirePost` to neutralize the `FlightCtrlState` if our input lock is active.

@FloFri btw thanks for helping to debug this issue. Here is my last update:
https://www.dropbox.com/s/i9all5lzlenlwvh/RemoteTech_v1.6_alpha-alpha-3.zip?dl=1

**Comment by Peppie23** [comment]
hmm ok it doesn't work. Neutralize the ` FlightCtrlState` also cuts the engine every time you focus an input :weary:

**Comment by pjf** [comment]
I'm *hugely* appreciating all the work being done here; I also play under Linux, and any improvement is a *wonderful* thing.

As an aside, one terrible work-around that I use under Linux is to manually *pause the game*, do my typing in RemoteTech and/or other input windows, and then resume. It's not ideal, but it used to be the only way to make sure numeric inputs didn't trigger action groups (oh, the !!fun!! I used to have entering numbers into MechJeb before switching to AGExt for my action group controls...).

**Comment by erendrake** [comment]
X and Z are special cases in the code that squad has made exempt from all
locking. in kos we have to get pretty aggressive with both keys by
unbinding them from their tasks and then rebinding on blur. it is not an
ideal situation

**Comment by Peppie23** [comment]
I saved the current throttle before neutralize the `FlightCtrlState` and it looks ok for me. It can also resolve #245 but i'm not sure :/ here my branche: https://github.com/Peppie23/RemoteTech/commit/53d652f8a27f39b8f48a554acd1cb6390f54510d if someone wants to fight with that issue

**Comment by henrybauer** [comment]
FYI a workaround is to go into the settings in the main menu and change the action groups to be fired by the numeric keypad.  Then you use the number keys above QWERTY to type numbers, and the numeric keypad to fire action groups.

Since there's also a bug on Linux that the numeric keypad doesn't work as numbers, the two bugs sort of cancel each other out. :)

**Comment by pjf** [comment]
> FYI a workaround is to go into the settings in the main menu and change the action groups to be fired by the numeric keypad. Then you use the number keys above QWERTY to type numbers, and the numeric keypad to fire action groups.

I love you so much right now.

**Comment by SirDiazo** [comment]
Okay, I had this issue pointed out to me and I had something of a brain wave that I hope works.

The base issue is that KSP doesn't lock everything with InputControlLock so that is the issue to actually fix rather then every mod getting it's own workaround.

So, I did that and it can be found here.
http://forum.kerbalspaceprogram.com/threads/108561

A simple mod that unbinds/rebinds keys on request from your mod to enforce a control lock.

It also includes a backup feature so that if a crash (or Alt-F4) happens with the lock engaged (and the keys unbound) it rebinds the keys on the next start of KSP.

As I envision it, that should solve everyone's issues with this problem.

To make sure developers who use this aren't tying themselves down, I release the code into the public domain so that it can be maintained by people other then me.

**Comment by Baughn** [comment]
Great idea!

But please don't just release it into the public domain. Apart from issues of safety (you're missing an indemnifying clause, or indeed any clauses at all), it isn't legal for you to release code into PD in all jurisdictions, so not all people can legally use your code at all. Instead, just use a highly permissive license such as MIT.

**Comment by Peppie23** [comment]
Merged into 1.7
