### ISSUE TITLE
Request: pre-target antennae in VAB/SPH

### ISSUE THREAD

**Issue by cerebrate** [RemoteTechnologiesGroup/RemoteTech#257]
Exactly what it says on the tin.

Because in that crowded orbital-insertion phase of flight (manage the burns, drop the lower stages, blow the fairings, extend the solar panels, activate the antennae, etc., etc.), while most of these things can comfortably be delegated to action groups, the one thing that can't is targeting said antennae, which has to be done the old time-consuming right-click way.

In theory, of course, I can target them on the launchpad/runway, but in practice:

(a) Very often, the relevant antennae are buried under a fairing at this time, and;

(b) It would be awfully convenient to save the standard antenna configuration of re-usable vessels right in the .craft file instead of setting it up again each time.

**Comment by Pharylon** [comment]
I've thought about this one before, and how useful it'd be to just be able to target the satellite I have in Kerbostationary orbit above the launchpad. +1 from this user.

**Comment by jdmj** [comment]
I'd say it's too much of a hassle for arguably minor (if any) gameplay gain.
(a) Press 'M', set the dish target through the RT toolbar. You don't need to activate it to set the target, you may do that later with the action group.
(b) would probably need a ton of otherwise useless logic in editor scene: get satellite IDs, check if your saved target is still present in the game, if it isn't - default to something and/or display a warning, plus additional interface for target selection in editor, and probably even more issues I didn't even think about. Each of the above presents potential bug nesting places.

**Comment by Shaggygoblin** [comment]
I don't use cargobays, fairings all the way here.  opening the map to target the entenae while on the pad for 5 sats in one inline fairing, all having the same name from adding them as payloads from the subassemblies, it is worth the effort to make this feature happen.  would be happy to assist in squashing resulting bug nests that result.
