### ISSUE TITLE
Duna Contracts Appear Long Before Access to Duna-Capable Antennas

### ISSUE THREAD

**Issue by Pharylon** [RemoteTechnologiesGroup/RemoteTech#344]
Subject pretty much says it all.

**Comment by ArSn** [comment]
Well then ... maybe you can do a manned flight before the duna-capable antennas are available?

I am only wondering what we should do otherwise now, make the duna capable antennas available earlier? It is A) not mandatory to do the missions as soon as you get them and B) you can as well do a manned flight.

That said, it is also pretty difficulty to do remote missions to duna anways, as the delay gets quite high already (depending on the interplanetary constellation of course).

Don't see an actual issue here.

**Comment by Peppie23** [comment]
Hi @Pharylon,
thanks for your task but i'm not sure what we should do? What would your suggestion for this task?

---
I mean, i also play on a "[really hard-career game](http://i.imgur.com/oWvZBMq.png)" and currently i also have a discover Duna-Contract but i am far far away to fly with a manned vessel or even with a satellite to Duna.

**Comment by Pharylon** [comment]
Wow, that's a hard game! :D I'm playing a fairly hard game right now, but not quite that hard (it's basially the "hard mode" options, with the monetary penalties and rewards both increased - I didn't enjoy feeling starved for cash). 

I dunno if you think it's not an issue, then maybe it's not. But, I don't think it should ever be easier to send manned missions to Duna than probes, especially just because you don't have the right antenna yet. While probes can be a lot cheaper, in normal difficulty games, where funds are pretty loose, I think that's where the game actually is with RemoteTech.

Nor do I think the time delay is a big issue, if you're not trying to land (even easier if you have KOS). Orbital insertions - or even flybys! - are not particularly hard. In my mind, I see two solutions: one extreme and one simple.

The simple one would just be to create a new antenna that reaches Duna most of the time, but not always. Say, it covers Duna 80% of the time. This keeps the player wanting a better antenna later, but they can reasonably get some science early.

2. Move to a more realistic antenna range model, like the AntennaRange mod uses. So you can send a probe to Duna using a lesser antenna, but it has some sort of trade of (more power, less science, etc) due to being beyond it's optimal range.

**Comment by Peppie23** [comment]
Hi @Pharylon,
yeah i know the problem. I'm currently working on a "Frequency/Spectrum"-Branch to get a bit more realistic but i'm not sure if i'll merge this into the RemoteTech-Master.

This feature will include:
- selecting a Spectrum like "S-Band", "X-Band" etc..
- Not all antennas will have all spectrums (to get a bit of variation)
- selecting a difffrent Frequency for the selected Spectrum (this causes that also your omni, will increase/decrease the electric charge, the time for science transmissions and the range. Dishes should always have a better science transmission as a omni for the same frequency)
- Upgrading the Tracking Center will take effect for the range of mission control (or for "scanning" different spectrums)
- only satellites (antennas) with the same spectrum can be a relay for the connection
- maybe a difficult switcher as a fallback to the "old mode" (current mode) because this change will break your sat network

When i'm ready i'll open a topic to discuss my changes with other players and we'll see how the acceptance is, than we'll see if we merge this feature to the Master or not. You are also welcome to discuss.

---

But back to this topic. I wouldn't create a new antenna. If you want a early duna antenna so it's up to you to create a new Part.cfg, based on a current antenna to change the range. Would that be a possible workarround for you?

**Comment by Peppie23** [comment]
I'll close this
