### ISSUE TITLE
upgrade range of MissionControlSatellite @ KSC with building upgrade

### ISSUE THREAD

**Issue by JDPKSP** [RemoteTechnologiesGroup/RemoteTech#386]
this was suggested by user:johnsonwax on the KSP forum.
as the title says. The range from Mission Control could be linked to the tech level of the building itself, giving a practically infinite range at highest tech level, but only a range suitable for LKO at the base tech level.
MissionControlSatellites wouldn't need to be saved persistently, just have different range states defined as subnodes in the config for each tech level plus a named reference for which building to check techlevel for.
the check would be performed on load and whenever the building is upgraded. IIRC there is a relevant GameEvent for this.

**Comment by Peppie23** [comment]
good idea :+1:

**Comment by darqen27** [comment]
Yes

**Comment by Shaggygoblin** [comment]
+1

**Comment by Sigma88** [comment]
I had an idea which was a variation of what JDPKSP/johnsonwax propose, I'm posting this here because I think it could be relevant, if not I'll move it somewhere else:

I called it the NearSpaceNetwork (NSN), the general idea stems from the fact that KSC crappy antenna range encourages the user to put more satellites in orbit

NSN consists of 3 ground stations on kerbin's equator, 120° apart one from the other
I was thinking, unlock the first KSC antenna in the "Survivability" node with small range, maybe not even capable to reach KerbinSynchronousOrbit.
the second upgrage (node = FlightControl) would add the other two ground stations and raise the range to cover KSO
the third upgrade (node = AdvancedFlightControl) would raise the range to the current range (just outside Kerbin SOI if I recall correctly)

let me know what you think about this :)
