### ISSUE TITLE
Thick text buttons (lag issue)

### ISSUE THREAD

**Issue by Joshwoo69** [RemoteTechnologiesGroup/RemoteTech#388]

**Comment by Joshwoo69** [comment]
![screenshot 2015-05-01 20 25 12](https://cloud.githubusercontent.com/assets/7894419/7430082/3a2cd21e-f040-11e4-991d-0db3d4fa2dbd.png)
![screenshot 2015-05-01 20 22 36](https://cloud.githubusercontent.com/assets/7894419/7430083/3a2fd784-f040-11e4-8100-94bac9e9904c.png)

**Comment by markus-k** [comment]
Commenting out all the code in ModuleSPU.HookPartMenus() seems to resolve this issue, but removes functionality of course. it looks to me like its rendering the text on top of each other, creating thousands of layers which slows the game down...

**Comment by SirDiazo** [comment]
Looks like something went odd here.:

https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/1de113658e0a86d534b0f9f9762eac346b8d0783/src/RemoteTech/Modules/ModuleSPU.cs#L130

That line is calling the HookPartMenus() method every FixedUpdate frame for some reason.

**Comment by Peppie23** [comment]
Hi,
@markus-k i get the same results. The last two days i tried to figure out why this happens but without success :/ My last comment on our team chat was:
> i think the setValue on the BaseEvent is not updating the current item, it "creates" a new item at the same position ...

and this will also cause the lag.

@SirDiazo i also tried to call the HookPartMenus() once for each "context menue", but also without success. No one from the RemoteTechCrew changed this part of code, i think Squad changed something on the `UIPartActionWindow` or `UIPartActionItem` or `BaseEvent`

Any idea what we can do?

**Comment by SirDiazo** [comment]
If I had to guess? (And it's a total guess) I'd start with UIPartActionWindow.

I don't really know the UIPartActionWindow or UIPartActionItem classes, but the BaseEvent class is what the [KSPEvent] attribute creates, I cant' see how that would tie into what (I think) is ultimately a GUI issue.

**Comment by Joshwoo69** [comment]
I would also comment. I think science parts also are affected.

**Comment by cybercritic** [comment]
Moving the HookPartMenus(); from FixedUpdate in ModuleSPU.cs to OnStart seems to fix the issue.

**Comment by Joshwoo69** [comment]
Bump.
@peppie23did you see what cybercritic said? Is it possible?

**Comment by Peppie23** [comment]
Hi,

the idea of cybercritic would only fix the lag and the "thick text" issue but we'll loose the ability for time delayed actions. We can only hook the action buttons on the context menue from the FixedUpdate method. I've also tried to hook the menue via the [GameEvents.onPartActionUICreate](http://anatid.github.io/XML-Documentation-for-the-KSP-API/class_game_events.html#ae6daaa6f39473078514543a2f8485513)-event but the issue is still there.

It "looks like" that the `eventField.setValue()` always creates a new object. If i [count the elements of the context menue](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/FlightComputer/UIPartActionMenuPatcher.cs#L17) it will increase for each HookPartMenus() call.

What i've also tried:

 - remove the original ActionItem and insert a new one to the list = without success
 - calling the UIPartActionWindow.Update() after changing the ActionItem = without success
 - calling the UIPartActionItem.Update() after changing the ActionItem = without success
 - changing the label of the original ActionItem to string.empty = without success
 - formatting c:\ = without success
 - and many many other things = without success

**Comment by OzoneGrif** [comment]
It seems to be a conflict with another mod, because if I remove all the mods and keep only RemoteTech, the bug disappears.

**Comment by OzoneGrif** [comment]
I figured something out. As soon as there's a Mechjeb part, or a probe part on your vessel, the bug occurs.

If it's a vessel with only Kerbals, the bug doesn't occur.

**Comment by Joshwoo69** [comment]
Hmm i tested on probe cores but not kerbals...
however the this is still there :P and is a lag to those who have a pre release Version.

**Comment by Joshwoo69** [comment]
Close issue : fixed with latest  comit
