### ISSUE TITLE
v1.6.5 introduces phantom forces for SAS and for Flight Computer

### ISSUE THREAD

**Issue by hyperbolist** [RemoteTechnologiesGroup/RemoteTech#431]
RemoteTech v1.6.5 can put vehicles into an SAS and Flight Computer resonance that can tear them apart.
## SAS

With small reaction wheels the behavior is of sluggish or muddy controls which can eventually "settle down", though really the wheels are merely unable to overcome whatever force is perceived to be acting on the vehicle attitude.  As reaction wheels get larger the behavior transitions into continuous correction which results in a persistent wobble, and then on to breaking apart.

When RCS is activated, the vehicle will spend all RCS attempting to combat whatever forces are believed to be acting on the vehicle attitude.
## Flight Computer

It should be noted that the flight computer is able to hold attitude if the root part designated in the VAB is still controlling the vehicle.

But if the user were to "control from here" on a docking node, the flight computer will spin the vehicle out of control and tear it apart.
## Verification that RemoteTech is to blame

Uninstalling RemoteTech eliminates this behavior altogether.  Reinstalling RemoteTech brings the behavior back.  Using CKAN, if that matters.
## Reproducing

Here are 2 craft files for testing with and without RT installed.
- [Simple Station Tug](https://www.dropbox.com/s/4r72c9947c4pebw/Simple%20Station%20Tug.craft?dl=0) for testing with RemoteTech.  Put it into orbit, turn on SAS and change its attitude.  Try disabling/enabling the different reaction wheels.  Solar panels extended or retracted.  RCS on and off.  The phantom forces are easily seen and felt. 
- [Simple Station Tug NO RT PARTS](https://www.dropbox.com/s/1enh5g9d8siaj2a/Simple%20Station%20Tug%20NO%20RT%20PARTS.craft?dl=0) for testing without RemoteTech.  Put it into orbit, turn on SAS and change its attitude.  Notice that it does not exhibit the same strange behavior.

**Comment by rootfuchs** [comment]
Seems I have similar problems. I'm not sure if the 'phantom force' is simply that the pitch-up and pitch-down vectors are equal at some point.

If've tried to correct the attitude manually and noticed that it's impossible to pitch up or down at ths point.At some point it's seems an nearly equal opposing force is working against your pitch vector, bu most of the time the choosen vector seems to tip over into it's opposite direction. In that case pitching in one direction works only for an small period until it's tips over. Same with RCS activated (thats what got my attention). 
But every time you can roll and yaw in position. Activate the Flight Computer, Mechjeb ASS or Vannily ASS results in losing control and steering all over the scale. But if you 'force' the ASS into 'rolling' and 'yawing' into position (correcting the attitude manually so the resulting correction can only be rolling an yawing) it works fine, until the attitude-control has to pitch.

Possible way of dealing with this behavior:
Seems to me to cycle trough all possible ASS-Methods. Most of the time 1 of 3 Methods can adjust the attitude correctly. But the cycling is an question of time before the Maneuver. If that method fails, you can manual adjust the attitude by rolling and yawing into position. Activate Time Acceleration if you are correctly holding attitude and activating the ASS afterwards seems to reset the ASS behavior for me most of the time. 

Modlist as Text:
http://pastebin.com/ZNdBfA4X

Modlist for CKAN:
http://pastebin.com/JRGvHci3
http://www.rootfuchs.de/ksp_remotetech/installed_mods.ckan

The only thing I've altered is to add multiple Ground Stations in the RemoteTech_Settings.cfg for multiple Launch-Sites (red) and Tracking Stations (yellowish). File here:

http://www.rootfuchs.de/ksp_remotetech/RemoteTech_Settings.cfg

Persistens Save: and output.log:
http://www.rootfuchs.de/ksp_remotetech/persistent.sfs
http://www.rootfuchs.de/ksp_remotetech/output_log.txt

Hope it helps.

**Comment by rootfuchs** [comment]
As I failed to mention in my last comment. In the savegame the MunSat1-Probe is the potential Ccandidate. Currently I solved the attitude behavior, but still 20M out of an maneuver node to fullfill an contract.

PS: The savefile could although be used as testing candidate for this issue:
https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/439

MunSat1 has exactly this problem with various instruments. I've kept the data instead of submitting it. Maybe it's reproducible if you discard the data and try to collect and submit it.

**Comment by Gaiiden** [comment]
I have a similar problem with 1.6.7 - rather than open a separate issue I'll just comment here. I'm in the process of porting my 0.90 craft to 1.0.4 and *some* of my probes have an issue with SAS, I haven't determined yet why some do and some don't. Those that do, when they are loaded they begin to oscillate or spin - slowly at first but soon they are rotating wildly. If I remove RemoteTech the problem goes away. If RemoteTech is installed but I disconnect the probes by lowering all antennae/dishes, the problem goes away. So it's definitely something with the Flight Computer. On the upside however, all the FC commands work perfectly - the craft will properly hold positions set via the FC when SAS is disabled. So at least things are functional in that regard.

**Comment by blandau** [comment]
I have the same issue in 1.6.8. I didn't notice it around Kerbin at a 1500 Km orbit but at Minmus, where the signal delay is 0.16, I started getting wobbling. The satellite would roll back and forth (in the lower left) and when I turned SAS off it stopped. A few seconds later it started again because there was also a small reaction wheel.

As a test, I went in to RemoteTech_Settings.cfg and turned the signal delay off and there was no rolling for the same crafts. My theory, the on-board SAS and reaction wheel is being effected by the signal delay.

**Comment by Peppie23** [comment]
Hi, can someone test this issue with this build: https://www.dropbox.com/s/qfh06koi9bjalcs/RemoteTech-v1.7.0-dev.zip?dl=1

But be **careful**!!, this is the current [v1.7.0](https://github.com/RemoteTechnologiesGroup/RemoteTech/milestones/1.7.0) dev build. You should make a copy of your save folder.

**Comment by Gaiiden** [comment]
wow that new options window is amazing
ok meant to test this sooner but got busy. Wobble is still there. Seems slightly better tho - ship has a bit of precession but never spins completely out of control. [Video](https://youtu.be/8yvtkudRnkE)

**Comment by Peppie23** [comment]
Hey @Gaiiden,
thanks for testing. We've more than one issue for this, i think.

* 1. Wobbling with a probecore where it is not the root part
* 2. Wobbling with an active attitude program from the flight computer
* 3. and now yours. Wobbling with no attitude program but with activated SAS

Can you confirm that your wobble did not exists without RemoteTech ?

The "biggest" problem here for point one and two is our SteeringHelper ... here we need a complete overhaul. This is the cause for many unstable flights. I'll look for that after v1.7 is released.

**Comment by Gaiiden** [comment]
I thought the SAS wobble was a confirmed issue others reported as well. I posted about it in the thread a while ago. Flight computer locks on to assigned headings with no problems. In the case of this craft and others I've seen behave this way, my root part is not the probecore.

Confirmed issue does not exist when RemoteTech is removed.

**Comment by KSP-TaxiService** [comment]
Oh wow, it reassembles several test results (aggressive oscillation, buggy RCS thrust, signal-delay effect etc) observed during my modernisation of RT's PID controller (Issue #674).

I am happy to say the modernised PID controller is working much smoothly in RT 1.8.
