### ISSUE TITLE
Local control, connectivity glitch

### ISSUE THREAD

**Issue by crafty-geek** [RemoteTechnologiesGroup/RemoteTech#459]
A simple satellite body is registering as under local control and disconnected from KSC, when there's no autopilot component and it's on the launchpad.
Parts list:
    Probadobodyne Okto 2
    SCANSat radar altimetry sensor
    Z-1k rechargable battery
4@ OX-4W 3x2 photovoltaics
    Octagonal Strut
    Reflectron DP-10
(Launch stages of all stock parts plus 1 KER unit)

This glitch was initially noticed when a kOS module was included as well, however it still occurs once that is removed.  (Also, that clued me into the fact it's a connectivity glitch, not just local control issues - kOS self-updating boot code I have was failing to find a KSC connection.)

Could there be a glitch in the default antenna of the OKTO2?
Modlist, or logs, or whatever, available upon request.

**Comment by neitsa** [comment]
Hi @crafty-geek!

I couldn't repro the bug anymore with the exact same list of parts on the latest develop branch (currently b0b77da), so I'm closing this bug. If you feel the bug is still present please reopen a new issue and [follow our guidelines for issue report](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports).

This kind of bugs are hard to track by themselves without logs, save files, ship file, etc.

Anyway, thanks a lot for your bug report!
