### ISSUE TITLE
Flight computer and local control?

### ISSUE THREAD

**Issue by crafty-geek** [RemoteTechnologiesGroup/RemoteTech#460]
Any chance we could get a part which enables a lagless flight computer when under local control without a KSC connection?  Perhaps with a prohibitive power drain or something, if there are balance issues?

**Comment by erendrake** [comment]
It would be simpler for you to uninstall the mod if you dont want to use any of its features :)

**Comment by space-is-hard** [comment]
@erendrake : I think the problem he's having is that he's trying to use the flight computer on a manned vessel, but it's still enforcing the delay despite the fact that the pilot should be who the player is controlling, not KSC.

I don't know why he wants a separate part to fix this instead of just ignoring the delay if there's a kerbal in the seat.

**Comment by abarbe-** [comment]
Situation: manned flight, no KSC connection.  I want to use the more
precise flight computer interface, rather than keyboard input (yes, I'm
aware of caps lock).  I can't get the flight computer to respond (or indeed
show up) in this case, making me think the devs' assumption is the flight
computer is running at ksc.  Thus, the suggestion for a part which would
allow the passenger to key in commands locally.

**Comment by JDPKSP** [comment]
@abarbe- 
The flight computer is part of any probe core and will accept local control input. So as long as you have both a crewed pod and a probe core on board you will have access to the flight computer without any signal delays. If you want the crewed pods to come with a flight computer you could mod in the prerequisite RT modules in with a ModuleManager config akin to how the modules are added to probe cores.

**Comment by neitsa** [comment]
closing per @JDPKSP comment which explains how to do it. We don't plan to add this behavior as default in RT but it's easily configurable with something like this (where `XXXX`is a pod name):

```
@PART[XXXX]:FOR[RemoteTech]
{
	%MODULE[ModuleSPU] {
	}
	
	%MODULE[ModuleRTAntennaPassive]	{
		%TechRequired = unmannedTech // chose the tech accordingly
		%OmniRange = 3000
		
		%TRANSMITTER {
			%PacketInterval = 0.3
			%PacketSize = 2
			%PacketResourceCost = 15.0
		}
	}
}
```
