### ISSUE TITLE
Network line incorrect rendering

### ISSUE THREAD

**Issue by d4rksh4de** [RemoteTechnologiesGroup/RemoteTech#540]
Quite often in map and tracking station scene, the network line is rendered to the opposite way. On the first screenshot the line is rendered correctly: http://i.imgur.com/TXtSK9g.jpg when I rotate the view to right, the network line turns to opposite direction heading to nowhere: http://i.imgur.com/nkevAXT.jpg This is in KSP 1.1. In KSP 1.0.5 the line will vanish at the time.

**Comment by d4rksh4de** [comment]
I'm not able to reproduce this in PR #544, it appeared only in my own custom build.

**Comment by d4rksh4de** [comment]
I was able to reproduce this issue with #544 When I zoom out, the line faces to other direction: http://imgur.com/a/Amlm0 When I zoom out even more, it goes beck to the correct direction http://imgur.com/J5MKO3O

**Comment by d4rksh4de** [comment]
It occurs more likely if the line needs to be drawn between long distances, eg. from Kerbin to Jool.

**Comment by neitsa** [comment]
Hey guys!

I could also repro this bug, but I'm going to push it onto the "Obsolete" cat. and close this issue at the same time.
As we are planning to move on with RT on top of the CommNet code, which already has connection lines visualization support implemented, I feel this issue is no longer relevant. I don't think we need to devote time to patch it as the code will disappear in the upcoming release (that is, right after 1.8.0).

If you (and I) feels that at some point this issue should be re-opened (for whatever reason), feel free to do so.

Thanks a lot :)

**Comment by neitsa** [comment]
Re-opening and linking to #711 as the bug re-surfaced.
