### ISSUE TITLE
Suggestion: FlightComputer without Connection

### ISSUE THREAD

**Issue by Y3mo** [RemoteTechnologiesGroup/RemoteTech#561]
Currently the flight computer does not open if there is no connection or local control.

I suggest to allow users to "program" the flight computer (for that probe at KSC) even without connection and then relay the programming to the vessel flight computer as soon as a connection is available.

**Comment by ndng28** [comment]
Set `ControlAntennaWithoutConnection = False` in  RemoteTech_Settings.cfg

**Comment by ndng28** [comment]
[Use this mode](http://forum.kerbalspaceprogram.com/index.php?/topic/97924-105-remotetech-xf-remotetech-v169/)

**Comment by tomekpiotrowski** [comment]
Hmm, that would require implementing some kind of a queuing system that would need to be persisted in the save file. Even then it would not work unless the vessel was active.

Honestly that seems like quite a lot of work for a small improvement. I don't see that being implemented in the near future, especially since we are short on manpower.

I'm gonna close this for now. We can discuss it again some day if there is still interest in it being implemented.
