### ISSUE TITLE
Options window not blocking mouse wheel zooming at KSC

### ISSUE THREAD

**Issue by gnivler** [RemoteTechnologiesGroup/RemoteTech#603]
While scrolling through the options window, the KSC view is also zooming.  It doesn't look like clicking goes through the window though.

**Comment by neitsa** [comment]
Dev Note reminder: we might need to switch settings to use the new `GameParameters.CustomParameterNode` in KSP 1.2. See [this forum thread](http://forum.kerbalspaceprogram.com/index.php?/topic/149432-answered-how-to-do-multiple-columns-in-the-gameparameterscustomparameternode/) for some pointers.

See also if the debug window (ALT+F12) exhibit this behavior.

**Comment by KSP-TaxiService** [comment]
The RT debug window (ALT + F12) in both tracking station and flight scene does not have this scrolling bug but it does have the click-through bug. In addition, the list of RT vessels from the application button in the map view has both click-through and scrolling-through bugs.

I will examine both option-window and debug-window for the scrolling and click-through codes.

**Comment by neitsa** [comment]
@KSP-TaxiService : you might want to take a look at [this forum thread](http://forum.kerbalspaceprogram.com/index.php?/topic/100641-click-thru-gui/), especially Sarbian's answer.

**Comment by KSP-TaxiService** [comment]
RT does have the window mechanism of blocking scroll-through and click-through. But it was written in pre-KSP 1.0 so it was broken after KSP's GUI system was overhauled during the Unity transition. I fixed and revised the mechanism. 

But there is a non-fatal side-effect: when a RT spacecraft is selected from the RT App-Button list in the Map View (flight scene only; tracking station not affected), the screen is rotated around the focused spacecraft. It only goes away when the user's cursor moves out of the list. I can't fix this side-effect easily because the FocusOverlay.cs (for the App-Button list) is part of a local UI mess that does not utilise the AbstractWindow superclass fully.

**Comment by neitsa** [comment]
closed in  #695 by @KSP-TaxiService.
