### ISSUE TITLE
IR1-Robotics controll unit lacks SPU

### ISSUE THREAD

**Issue by TheToric** [RemoteTechnologiesGroup/RemoteTech#638]
from infernal robotics mod.

**Comment by KSP-TaxiService** [comment]
Infernal Robotics hasn't been updated since KSP 1.1 and I am seeing there is an active development on a fork of this mod ([link](https://forum.kerbalspaceprogram.com/index.php?/topic/170898-wip-infernal-robotics-next/)).

I will close this thread and see if there is any comparability patch required when this fork is officially launched.
