### ISSUE TITLE
FC is overcompensating or even spinning out with RCS enabled but ports set to ignore rotation.

### ISSUE THREAD

**Issue by jdmj** [RemoteTechnologiesGroup/RemoteTech#643]
Replication: have a simple probe with both reaction wheels and rcs. Tweak rcs thrusters for translation only. Changing orientation when rcs is disabled works as intended, but if rcs is enabled, it won't be able to hold direction and may spin out, depending on how torque from reaction wheels and (nonexistant) torque from rcs thrusters compare.

Fix:

```
--- a/src/RemoteTech/FlightComputer/FlightCore.cs
+++ b/src/RemoteTech/FlightComputer/FlightCore.cs
@@ -377,9 +377,15 @@ namespace RemoteTech.FlightComputer
                             /* end sarbian's code */
 
                             // This overestimates the usable torque, but that doesn't change the final behavior much
-                            pitch += (float)Math.Abs(thrusterTorque.x);
-                            roll += (float)Math.Abs(thrusterTorque.y);
-                            yaw += (float)Math.Abs(thrusterTorque.z);
+							if (rcsModule.enablePitch) {
+								pitch += (float)Math.Abs (thrusterTorque.x);
+							}
+							if (rcsModule.enableRoll) {
+								roll += (float)Math.Abs (thrusterTorque.y);
+							}
+							if (rcsModule.enableYaw) {
+								yaw += (float)Math.Abs (thrusterTorque.z);
+							}
                         }
                     }
                 }
```

**Comment by hvacengi** [comment]
A more complete fix would probably be to move to using `ITorqueProvider` to calculate torque instead of doing the math yourself.  You can see kOS's implementation here: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Control/SteeringManager.cs#L581-L609

(You may notice I'm also correcting the stock MoI implementation below that, but that should be fixed in the next release of KSP, but you may want to include it as well depending on the next RT release and the next KSP release timeline alignment).

**Comment by neitsa** [comment]
I couldn't replicate the issue anymore, although this doesn't mean it is totally fixed. Let me know if that works on not (in this case I'll reopen the issue). Thanks!

Related build is [RemoteTech-1.8.0-7-develop](https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/RemoteTech-1.8.0-7-develop).
