### ISSUE TITLE
RT-C tries to execute node too early?

### ISSUE THREAD

**Issue by WildLynxDev** [RemoteTechnologiesGroup/RemoteTech#661]
Conditions:

Ship under Local Control - yellow keypad.
There is some time before m. node.
Node is long burn. (looks like don't matter)
I set a time delay before node to round value, then watch the KER for "time before 1/2 burn" reach it, the click Execute.

Usually I do it with 0.1 seconds precision, considering game_time / real_time is about 20% with big ships.

Delay was 2hrs that time, but looks like it don't matter.

Usually, "remaining time" values in RT-C and in KER stay synchronized until burn started. But now RT-C sets the delay exactly 70 seconds too short. Ship is about 1200km from Kerbin, so, even if crew is sleeping instead of controlling the ship, speed-of-light delay cannot be that big. And looks like "70 seconds too early" effect don't depend on signal range, it's always the same.

I never allowed RT-C to start burn, if timing look wrong, so it might be pure display bug...

**Comment by KSP-TaxiService** [comment]
This bug is Flight Computer decrements the delay countdown using TimeWrap.deltaTime, which is floating point and can be off by -/+ 0.001. It is only noticeable in a long-delayed command like these pictures.

**Start (compare KER's Time to Node Burn and FC's countdown)**
![start](https://user-images.githubusercontent.com/22871614/43033456-6d4a4778-8cfd-11e8-9203-774003d265a1.PNG)

**End (FC's countdown runs too fast)**
![end](https://user-images.githubusercontent.com/22871614/43033457-70b79e42-8cfd-11e8-98cf-888f684a17da.PNG)
