### ISSUE TITLE
The rover steering and throttle PID's need work`

### ISSUE THREAD

**Issue by mferrie** [RemoteTechnologiesGroup/RemoteTech#674]
I was trying to make a rather small rover try to drive west for 100m at 5 m/s, but the dumb thing kept driving in semicircles, always overshooting its heading by ~90 degrees, and changing the wheel throttle wildly. Perhaps you could decrease the proportional gains and/or increase the derivative gains in the PID controllers for the wheel throttle and steering?

**Comment by adempewolff** [comment]
I also encountered this problem.  I think that those PID's were written long long ago as an experimental feature and haven't seen the light of day since then.  On the forums few people even know about the rover control tab.  I didn't notice any problem with the throttle PID though, just steering.

**Comment by KSP-TaxiService** [comment]
I gonna to take a stab at this.

Copied from Slack channel:
------
lamont [23:25] 
you should use the kOS pid loops



[23:26] 
i was writing my own automation code at one point and adopted it


[23:26] 
the pidloop looks like this:


[23:26] 
https://github.com/lamont-granquist/MechJim/blob/6a10e09b86b969b1b0ffe00881c6f4626ba52bd7/Source/PIDLoop.cs
GitHub
lamont-granquist/MechJim
MechJim - Kerbal Space Program Automation
 


[23:27] 
the way it gets used looks like this:


[23:27] 
https://github.com/lamont-granquist/MechJim/blob/577002bccd3558d53efcee873d4bb982540c9cdf/Source/Manager/SteeringManager.cs
GitHub
lamont-granquist/MechJim
MechJim - Kerbal Space Program Automation
 


[23:28] 
it uses 6 pids:


[23:28] 
https://github.com/lamont-granquist/MechJim/blob/577002bccd3558d53efcee873d4bb982540c9cdf/Source/Manager/SteeringManager.cs#L19-L25
GitHub
lamont-granquist/MechJim
MechJim - Kerbal Space Program Automation
 


[23:32] 
looking at the RT code, i’d replace the existing PID class, and then break up the FlightComputer class since if you put the 6-PID code into that it’ll get messy.  all the PID code should most likely be extracted from FlightComputer into a new class.
