### ISSUE TITLE
Error when signal lines are shown in a map or in the tracking station

### ISSUE THREAD

**Issue by jarosm** [RemoteTechnologiesGroup/RemoteTech#693]
When signal lines are shown in a map view or in the tracking station, then an error "Trying to create a material from string - this is no longer supported." is generated. This error is generated on scene change and when cycling through displayed connection lines types by clicking on a button in the tracking station.

RT version: RemoteTech-1.8.0-5-develop

Output log: https://dl.dropboxusercontent.com/u/69160140/RemoteTech/output_log.txt
Persistent file: https://dl.dropboxusercontent.com/u/69160140/RemoteTech/persistent.sfs
List of mods: https://dl.dropboxusercontent.com/u/69160140/RemoteTech/mods.txt
(There are three probe relays in the persistent file, which has only stock, RemotechTech and USI Reactor Pack parts)

**Comment by neitsa** [comment]
hello @jarosm, thank you for your bug report!
This is a known issue (problem is located [here](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/UI/NetworkCone.cs#L62)) : unity doesn't  like embedded sharers. A fix would be to move out the shader, compile it to an external file, locate the file within RT and load the shader.

The thing is, we'll soon move RT on top of CommNet and this piece of code we'll be removed in the process. There are other bugs that we'd like to address in the meantime, knowing that this  bug we'll disappear with the next major RT version.

I'm still keeping the bug opened, but I can't  say it will be fixed in the next minor bug fix release.

Anyway, thanks a lot for your detailed issue report 👍 , it's always a pleasure to have well documented issues.

**Comment by jarosm** [comment]
I understand. It's not gamebreaking, so I can ignore it :)

**Comment by PiezPiedPy** [comment]
Just tested the pre-release, worked fine for me on KSP 1.4.5
