### ISSUE TITLE
Conflict of the extend/retract state of an antenna in editor

### ISSUE THREAD

**Issue by sviat9440** [RemoteTechnologiesGroup/RemoteTech#698]
os: Win 10 64b
ksp: 1.2.0.1586 64b
log: [KSP.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/587207/KSP.txt)
save: https://yadi.sk/d/4vAsw0HJyMXUz
problem: [2016-11-12_16-08-14.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/587209/2016-11-12_16-08-14.zip)

**Comment by neitsa** [comment]
@sviat9440 : Thanks for your report. Can you tell me if I understand your problem correctly?

Looking at your video, in the VAB all your DTS-M1 antennas are retracted but when you launch the ship (from the VAB), when it sits on the launchpad all your DTS-M1 antennas are starting deployed? Right?

If that's the problem I'm not sure it comes from RemoteTech (although that's still a possibility that there's something wrong with our config, but it sounds strange that this bug never surfaced before).

* What happens if, on the KSP center scene, you click on the launchpad (which should open a menu to load a ship) and load your ship from here rather than loading it from the VAB?

* As a simple test, could you try to load your ship **without** RT being loaded at all? 
      * Remove RT completely from your `GameData` folder (you can zip the whole RT folder)
      * Start KSP
      * Load your ship in the VAB
      * Try to launch it from the VAB
      * What happens in this case on the launchpad? 
      * Are the DTS-M1 still deployed? If yes, that's a stock problem, if not, there's a problem on our side...
      * (to end the test: quit KSP, and get RT back)

Looks like a stock bug to me, but I'm still unsure...

As a side note, as the DTS-M1 is a stock antenna, the RT config for the DTS-M1 is this one in `RemoteTech_Squad_Antennas.cfg`:

```
@PART[mediumDishAntenna]:FOR[RemoteTech]
{
	@MODULE[ModuleAnimateGeneric]
	{
		%allowManualControl = false
	}
	
	%MODULE[ModuleRTAntenna] {
		%Mode0DishRange = 0
		%Mode1DishRange = 50000000
		%EnergyCost = 0.82
		%MaxQ = 6000
		%DishAngle = 45.0
		
		%DeployFxModules = 0
		%ProgressFxModules = 1
		
		%TRANSMITTER {
			%PacketInterval = 0.3
			%PacketSize = 2
			%PacketResourceCost = 15.0
		}
	}
	
	%MODULE[ModuleSPUPassive] {}
}
```

**Comment by Netrilix** [comment]
I'm not able to view the zip file right now, but it sounds like what you're describing is an Action Groups issue. Did you attempt to add the antenna to an Action Group and accidentally add it to Stage (the default group when you open the screen) instead of the Action Group you actually wanted?

**Comment by YamoriYuki** [comment]
@sviat9440 I checked your save file and your DTS-M1s are set to start deployed. All you need to do is r-click each group of them and click "start retracted". You will see a a quick antenna animation and your antennas will start retracted. This has been in RT for a while.

**Comment by KSP-TaxiService** [comment]
Posted the reproduction steps given by Yamori for RT 1.8.0:

> Having a craft with a deployable antenna, use the "Start deployed" action. The antenna will deploy. Save the craft and reload it. The antenna will not redeploy in editor but will if you launch the craft. To correct this behavior as a player, you just need to use "Start retracted" in editor before launch/save.

![bug](https://cloud.githubusercontent.com/assets/22871614/20307837/489578c6-ab7c-11e6-93f4-75fefc62ed9a.png)

**Comment by ShotgunNinja** [comment]
If you are using the `ModuleAnimationGroup `(or similar) to drive the extend/retract animation, be advised that in the editor it doesn't call the `EnableModule()/DisableModule()` functions from `IAnimatedModule`.

**Comment by YamoriYuki** [comment]
We may be able to MM patch antennas back into using `ModuleAnimateGeneric`, which is fine for RT as it handles everything the `ModuleDeployableAntenna` does (at least from RT point of view).
Needs to be properly tested.
