### ISSUE TITLE
Logging connection state 

### ISSUE THREAD

**Issue by diomedea** [RemoteTechnologiesGroup/RemoteTech#716]
RemoteTech v. 1.8.4. In flight, with both output_log file and the debug console, RemoteTech "spams" a flow of "RemoteTech: Flight: <vesselID> Has Connection: False/True". Doing a coarse measure, about 2 such log messages per vessel with an antenna per second in game (done at 25 FPS, if that is useful). 
While I understand all those messages could come useful for debugging RT events with a version under development, they aren't providing but a loss of performance and too large log files to normal users.

I would propose that, if really RT states are that useful, they get recorded on log only when there's a change (for any vessel, going from false to true or the opposite). Even better if the message could tell the actual vessel name (the vessel ID requires users to check against savegame data) and UT of the event.

**Comment by KSP-TaxiService** [comment]
Hi, can you send your output_log file, please? I need to see the list of your mods installed. I track the message to RT's API which is for third-party mods to use. Under the KSP and RT mod only, this message is not written to either log or debug console because API is not used.

**Comment by neitsa** [comment]
Thanks for your report @diomedea !

Just some notes to add to @KSP-TaxiService answer.

The incriminated message [is here](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/API/API.cs#L78) : it's a message from the RT API.

There's only one reference from RT code to this API, which is in the [debug window](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/UI/DebugWindow.cs#L268). This code is only called when you actually push a button (Run button) in the debug window.

Funny to see that it escaped our tests because it is never called repetitively by RT, which means that one of your mod is actually calling it.

@KSP-TaxiService / @YamoriYuki  : we might consider removing the debug messages altogether from the API if mods tends to call some of them repetitively. Or else provide an option (setting ?) to enable / disable them.

**Comment by diomedea** [comment]
Please find [here the output_log](https://www.dropbox.com/s/18qwopcrqryrt55/output_log.zip?dl=0). 
As correctly guessed, I have many add-ons with that game. Didn't think the log could be started by another.

**Comment by YamoriYuki** [comment]
@neitsa
If possible I would just change the log level or something similar, to keep the logging in debug build. Any modder should be able to build his own debug build of RT and use that to observe the log.

**Comment by diomedea** [comment]
Thanks for suggestions above. I checked with another KSP 1.2.2 install with only RT 1.8.4 and Kerbalism 1.1.8 (plus Module Manager), that was all it needed for the log spam to show. Therefore believe your API is called too often by Kerbalism.

**Comment by KSP-TaxiService** [comment]
@neitsa , @YamoriYuki 
Looking at the RTLog.cs, I discover this [gem](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/RTLog.cs#L96) where `verboseLogging = GameSettings.VERBOSE_DEBUG_LOG;`. In other words, there is already the stock-KSP option (General Settings) to disable/enable the verbose logging.

![thissetting](https://cloud.githubusercontent.com/assets/22871614/22249604/a1854b30-e27e-11e6-905c-7a03392cc76c.png)

diomedea, is this option enabled on your side?

**Comment by diomedea** [comment]
Sure I had verbose logging on, turned off after you showed me what code produced those messages. Must say I'm almost always using verbose logging to find/document issues, but even with verbose on have logspam only when there is definitely something worth reporting.

**Comment by KSP-TaxiService** [comment]
I am with you, diomedea. In a newly-created branch, I remove those messages that just say the same thing as the function and leave this commit for other members to review.

**Comment by KSP-TaxiService** [comment]
Thanks diomedea for reporting this logging spam. With the suggestion from someone in the team, an additional condition is added to log messages of API and Assembly levels in the debug mode only. This shouldn't show up in a normal mode.
