### ISSUE TITLE
When installing this mod for the first time the antennas of existing probes are disabled

### ISSUE THREAD

**Issue by mikeloeven** [RemoteTechnologiesGroup/RemoteTech#717]
If you install this onto an existing save currently active probes have their antennas turned off regardless of their state (extended / retracted) the mod needs to check the antenna state of existing probes and ensure that this is properly preserved. If this is not possible than there needs to be a debug setting allowing the command restriction to be temporarily disabled to restore connections to existing probes effected by this problem. As it stands adding this mod to an existing save breaks all active probes/satalites

**Comment by KSP-TaxiService** [comment]
Hi,

We are aware of this issue for some time. 

For a quick workaround, a restriction-bypass setting is available in the RT option window so that you can update/restore your antennas in absence of working connection.

![cheat](https://cloud.githubusercontent.com/assets/22871614/23336854/4dd488f4-fc17-11e6-9d42-e36ad964bb41.png)

On a long-term fix, it is not possible to do so because KSP simplifies the whole space communication to the baby scope. The stock antenna modules (`ModuleDeployableAntenna` and `ModuleDataTransmitter`) are lacking critical information (like where to aim a dish antenna at? Is a non-deployable antenna activated?) we would need to configure our own antenna modules to match to the pre-RT antenna states. This is why the bypass setting I mentioned is included to the RT option window.

**Comment by KSP-TaxiService** [comment]
@mikeloeven Do you have any comment or question regarding this matter? If not, I will archive this report, given that it is difficult to fix.

**Comment by mikeloeven** [comment]
Actually the workaround you already added was the way to go and it works
