### ISSUE TITLE
Spam of "found and load save settings" that reduce performance.

### ISSUE THREAD

**Issue by GonDragon** [RemoteTechnologiesGroup/RemoteTech#719]
OS: Windows 10  (10.0.0) 64bit
Kerbal Space Program - 1.2.2.1622 (WindowsPlayer x64)

**Issue:** When you grabs an antenna in the VAB, or fly a vessel with an antenna, the game starts to slow down and lag. This happends since the last update (RemoteTech-1.8.5)

When I grab something capable of communication (antenna or probe) in the VAB, the game lags a lot. The same happens when I fly a vessel with antennas. So, I looked at the Debug Console, and the game were spaming this message:

[http://pastebin.com/XbEZ7xFW](url)

I just were a few minutes in the game, and the log file grew upto the size of **20 mb**. Here is the log:

[https://www.dropbox.com/s/zepif445cpa6r2b/KSP.log?dl=0](url)

**Comment by Shooshpanius** [comment]
Same problem. When installing the antenna on the craft, the game slows down.

**Comment by YamoriYuki** [comment]
@GonDragon: With stock + RT only the problem is not present so it's a bug in code for third party mods to use. You have a LOT of mods there. If you use CKAN, you can export the list for easy installation elsewhere (that would be us for testing this).

@Shooshpanius: Could you share your log and possibly CKAN mod list too? Maybe we can eliminate some (hopefully many) mods from GonDragon's setup from testing, which one makes this show up.

**Comment by YamoriYuki** [comment]
This problem is caused by e78330c that prevents settings instance from being kept, therefore loading it every time it's needed without success. All this because there's no ground station called "Mission Control" in your save game settings. The fix will be simple, just need to wait for the team.

In the mean time, you can go to RemoteTech_Settings.cfg in your save game folder and rename ground station called "KSC Mission Control" to just "Mission Control". This probably won't cause other issues but it's not guaranteed.

**Comment by Shooshpanius** [comment]
@YamoriYuki https://yadi.sk/d/bdq3NTkX3F2hVg logs
