### ISSUE TITLE
Antennae will not work with SETI-mods

### ISSUE THREAD

**Issue by argentrolf** [RemoteTechnologiesGroup/RemoteTech#727]
O.S: Win 7 64bit
KSP: 1.2.2.1622 64bit
Problem: As in the title. I haven't narrowed down ether it is ALL of the SETI-mods or just one but I will update when/if that changes...
Reproduction steps:
    Put simply:
   Installed RT and tested... working (I think, at least the antenna functioned)
   Installed UbM... working (again, antenna functioned)
   Installed all SETI-mods and peripherals... Aaaand engineer tab said that I hadn't connected an antenna (with all three available, using CTT, attached)
   Went to launch pad... no connection, no launch
        
Logs:
 not quite sure it applies in this instance and not sure where to find that. If you need it, let me know and i will edit to include it.

Installed Mods: 
 At the time of the issue occuring:
   CTT
   Contract Configurator
   CustomBarnKit
   RT
   SETI-
      contracts
      custombarnkitconfig
      greenhouse
      probeparts
      rebalance
         materialsgoo
         reactionwheels
      UbM
      ModuleManager

Persistent save:
 New Start

Screenshot:
   This was taken during an earlier ttempt before I stripped the mods out, but everything else is as noted above.
    ![help](https://cloud.githubusercontent.com/assets/28812856/26263196/560759ae-3c9d-11e7-963e-4e458b9fd3af.png)

I would really like to use both this AND the SETI series... if I'm missing something or if its an actual glitch, I'd appreciate the help.

**Comment by argentrolf** [comment]
well... i give up... after installing the SETImods RT simply refuses to work at all. even after uninstalling ALL of them.

**Comment by KSP-TaxiService** [comment]
Hi Argentrolf,

Thanks for reporting this potential issue. The log you need is located in the KSP_x64_Data folder.
![image](https://cloud.githubusercontent.com/assets/22871614/26273479/b121216e-3d63-11e7-85ed-fd7203bce5c4.png)

Please upload this log of both SETImods and RT installed together so that we can look into.

The SETImods has a number of configs, included these two configs for RT:
> Download: SETI RemoteTechConfig v1.2.2.0 (for RemoteTech 1.8.2+)
>This is a SETI config for RemoteTech, adding ground stations, changing the KSC range to cover the whole kerbol system (when not obstructed), setting signal delay to false and tweaking some colors.
Required Mods: Remote Tech

>Download: SETI ProbeControlEnabler v1.2.2.1 (for RemoteTech 1.8.3+)
> This is a SETI config for RemoteTech, allowing probe control without connection. Thus a connection is only required for science transmission. Unfortunately this may remove the built-in omni antenna from probes (but not from manned command pods).
Required Mods: Remote Tech

Thanks!

**Comment by argentrolf** [comment]
cool. give me a bit to restore a stock install, then ill try double checking with ONLY seti and rt, see if that does it too... and then upload the logs

**Comment by argentrolf** [comment]
alright, installed mods are visible in the rocket description:
![screenshot0](https://cloud.githubusercontent.com/assets/28812856/26276857/fbe18a22-3d45-11e7-994e-ba65c8fdee12.png)

and the log file:
[output_log.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/1016265/output_log.txt)
ok, i almost missed it, wasnt in ksp_x64_data... for me it was in ksp_data... as an aside, could that itself cause problems or is it just settings/which exe i launch with?

**Comment by KSP-TaxiService** [comment]
Thanks for uploading the output_log.txt. 

First, since you are using Windows OS x64, try launch your KSP_x64.exe as shown below because the uploaded output_log.txt indicated it came from older version KSP (1.0 or earlier). The new output should be inside KSP_x64_Data folder after.

![image](https://cloud.githubusercontent.com/assets/22871614/26357147/f6a9663e-4000-11e7-98ef-7cac7987d8a3.png)

Second, your output log somehow stops in middle of the KSP's Squad loading screen and is incomplete. I am unable to determine any mod listed or its version there.

Third, based on your screenshots provided, something indeed prevented RT antennas from registering to Engineer's Report properly. Can you tell me the versions of your RT and SETI mods, please? Our latest RT version is 1.8.6.

**Comment by argentrolf** [comment]
sorry for not responding, lost internet for a bit. i will try the x64.exe and send the output log after, i currently have neither installed, but give me about ten minutes (if your on right now) and i can have it set up... maybe it was just something to do with how the launcher was starting my game? if so, that means im in the wrong place, lol.

**Comment by argentrolf** [comment]
[output_log.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/1033729/output_log.txt)

new output log (this time in the launcher folder...) and still no antenna in the engineer. freshly reinstalled and the only mods were RT 1.8.6, SETIrebalance 1.2.2, and MM 2.7.6.

**Comment by KSP-TaxiService** [comment]
@argentrolf I think you are right about how the launcher was starting your game. The latest output_log you provided is incomplete (it stopped writing only moment after launching).

Please try to launch your game from `C:/Users/HP/Desktop/Kerbal.Space.Program.v1.2.2.1622` folder. It should load its files from the main directory instead of `Launch_Data` folder
![image](https://cloud.githubusercontent.com/assets/22871614/26552898/be8f931c-44bb-11e7-8469-719ffb326913.png)

**Comment by KSP-TaxiService** [comment]
Hi,

A gentle reminder on this request.

Thanks!

**Comment by argentrolf** [comment]
sorry it took so long, i think you can call this resolved... i dont know what changed, but now RT is working with everything (the engineer still says no sometimes but i think thats just incompatible parts), ive tried going back to recreate the issue as well, and the same things that started it... dont. like i said, idk what changed, but i do appreciate your help. it had to have been something on my end. I will look a bit deeper and if i ever figure out what i screwed up, ill let you know... maybe there would be a way to idiot-proof my idiocy, lol

**Comment by KSP-TaxiService** [comment]
Good to hear that it works on your side. 

I will close this thread.
