### ISSUE TITLE
Joystick can bypass Signal delay

### ISSUE THREAD

**Issue by Domi1993** [RemoteTechnologiesGroup/RemoteTech#742]
When use a joystick to control Space ships there is no Signal Delay, this means i can use it to control the Vessel in real time.

Throttle Controls from the joystick are delayed

EDIT: Version from RemoteTech.version

	"VERSION":{
    "MAJOR":1,
    "MINOR":8,
    "PATCH":7,
    "BUILD":0

**Comment by KSP-TaxiService** [comment]
Hi, can you try with the latest RT 1.8.9, please?

In addition, what joystick hardware are you using? I am going to try to reproduce the delay bug with my Xbox360 controller.

**Comment by Domi1993** [comment]
in 1.8.9 it happens too, Throttle is delayed but the other not (roll, pitch ,yaw)

Joystick is Extreme 3D PRO from Logitech

**Comment by KSP-TaxiService** [comment]
Hi,

Thanks for your details. I have two questions about this bug.
- I mapped my controller to KSP input rotation axes ([Clicky pic](https://i.imgur.com/6DQq6xU.png)). Is it the same settings used by your joystick? 
- Are you on stock SAS (Key T) when the bug is happening? How about disabling the SAS and try rotating?

I reproduce this bug only if I have stock SAS on.

**Comment by Domi1993** [comment]
I mapped my controller to KSP input rotation axes (Clicky pic). Is it the same settings used by your joystick?

Yes i have this Joy0.3 ... in the settings.

When i find time i will try what happens with the SAS

**Comment by Domi1993** [comment]
Yes with Stock SAS off it is delayed
