### ISSUE TITLE
PartAction Menu issues

### ISSUE THREAD

**Issue by inkognito1100** [RemoteTechnologiesGroup/RemoteTech#749]
[KSP.log](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/1962802/KSP.log)
After craft losing signal, throttle control sliders in all engines menus start to slide with a few seconds lag. Not only on craft that lost signal, but on all crafts even in hangar. Also crafts start to 'dance' on launching table.
I'm sure it's RemoteTech bug, because I cant repeat it when I delete this mod.

**Comment by m4ti140** [comment]
Are you using Kerbalism? I have the same issue and I have a sneaking suspicion it's related to Kerbalism support for RT. The FPS drops to unplayable levels whenever the signal is lost on active vessel and goes back up when it's regained.

**Comment by JetSetMiner** [comment]
I've had a similar experience. I do not have Kerbalism. The sliders for anything I've built with symmetry start lagging (i.e. just reacting slowly) and the symmetry between parts get disconnected, meaning if I added four engines in quad symmetry, I have to change each one's thrust limit individually; they are no longer linked. This happens while I'm building in the VAB. Have not noticed any link with losing signal, or anything while running the simulation. Same goes for control surfaces in the SPH; anything with symmetry. I removed Remotetech and symmetry worked fine again. Reinstalled Remotetech and the problem is back.

**Comment by JetSetMiner** [comment]
Addendum: Service module shrouds and interstage nodes in fairings also stopped working. Works again when I delete the Module Manager cache, for one session. When I reload it's broken again. Consistently fixed when I remove RemoteTech. Hope this means something to someone.

**Comment by KSP-TaxiService** [comment]
Hi @inkognito1100 @JetSetMiner,

I believe you refer to the issue #748 of sluggish response on Part Action menu, which was recently fixed. It is not related to Kerbalism. 

Please try the DLL file available there ([linky](https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/748))

**Comment by JetSetMiner** [comment]
Hi, yes that description fits perfectly. Will try asap after work, thanks so much!

**Comment by KSP-TaxiService** [comment]
From the issue linked,

> Unfortunately I have mixed results. The lag is completely gone, but after a while the symmetry gets broken again and interstage nodes and the shrouds of service modules stop working. But I have found putting down 2 fairings that are mirrored and then picking up the other one restores the nodes. I'm sorry I can't make a comprehensive video like ChippedChap.

Hmmm, I do not see any code in RemoteTech to handle with fairing and symmetry side. Got simple reproduction steps I can use for debugging? 

Just changing the throttle value of one of quad-symmetry engines is enough?

**Comment by JetSetMiner** [comment]
I had little time yesterday, so couldn't reproduce it consistently. So far all I can say is that it happens "after a while" -- I believe that is the technical term. After launching, playing for a while, then returning to the VAB, the symmetry is broken again (but the lag never returns, so that's sorted). As soon as the symmetry is broken the shrouds and fairings are also broken. But I've found placing two service modules in symmetry, or two fairings, I can right click on one, change the shroud open or close setting, and then *pick up the other one* which will then show whatever setting I just changed. So I click "open shroud" on the one I place and nothing happens, but when I pick up the other one in the symmetrical pair, that one's shroud is open. The same for the fairings: I can put down a pair symmetrically, right click and enable interstage nodes. Then I pick up the other one of the two, and it suddenly shows the nodes. I suspect the object attributes get intercepted by RT and then passed back to Unity and something special has to happen to the nodes and shrouds attributes, but that something doesn't happen. What I can guarantee is that it happens every time for me after a while. I just can't find a guaranteed way to make it happen in the beginning at will. In the mean time, though, I can play just fine now that the lag is gone and I can do the symmetry workaround, so please don't think I'm complaining.

**Comment by KSP-TaxiService** [comment]
Hi @JetSetMiner,

I can't reproduce it consistently either (never encountered it so far). But I put an extra check for RT not to do anything to PartAction menu if the scene is in Editor.

Can you try again with this new DLL?
[Plugins.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/1997816/Plugins.zip)

**Comment by inkognito1100** [comment]
@KSP-TaxiService 
Sorry for not responding - had no time for KSP. I've tried .dll from #748 issue, now sliders and symmetry works fine for me. Thank you.
But I have new issue with RT and Kerbalism: if you switch off showing signal lines in flight, all crafts in crafts manager except the active one become marked with "no signal" icon, but as soon as you switch on signal lines, signal returns. I've asked Kerbalism author, he says it must be RT problem.
![screenshot292](https://user-images.githubusercontent.com/22282875/40056860-4a615f76-5855-11e8-978d-3bacf8895b92.png)

Should I open new issue?

**Comment by KSP-TaxiService** [comment]
Hi inkognito,

Good to hear that the fix resolves the PartAction menu lag on your side. 

Kerbalism author informed me on this signal issue and I added a fix to the codebase already. A next RT release should be out soon.

**Comment by inkognito1100** [comment]
Oh, nice to hear that.

**Comment by JetSetMiner** [comment]
Hi. You nailed it. I played with the above dll for a good few hours and could consistently go back to the VAB at any time and build manned and unmanned craft without any issue returning. Symmetry kept working, shrouds and fairings worked and I'm pretty sure Aids got cured. Thanks, especially as it seems this is a rather rare thing. Do you have any theories as to why only me? Interference from a different mod? Anyway, absolutely nailed. It was very satisfying when my unmanned Duna probe entered orbit successfully yesterday using the commands I queued up a week ago. Great mod.

**Comment by KSP-TaxiService** [comment]
Thanks for your confirmation on the latest change.

All I can think is third-party mod interference and I have no concrete evidence. I will push thee pre-cautionary check to RT codebase.
