### ISSUE TITLE
Can't enable SAS 

### ISSUE THREAD

**Issue by Nathankvl** [RemoteTechnologiesGroup/RemoteTech#786]
I have seen a post like that but I have another problem, the SAS and RCS icons are shaded and I can't do anything, I've put an antenna on the sputnik probe but the problem persists

**Comment by KSP-TaxiService** [comment]
Hi, kindly assist to provide logs, screenshots and KSP & Windows version for further investigation, per [link](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports)

**Comment by Nathankvl** [comment]
How can I put screenshots from steam here ?

**Comment by KSP-TaxiService** [comment]
You can download your steam screenshots to your desktop, upload to Imgur.com and link urls here. 

Also, don't forget to post ksp version and log for full investigation.

**Comment by Nathankvl** [comment]
https://imgur.com/a/7NGGFIE
https://imgur.com/a/Zgp7Mhj
Here's my problem

**Comment by KSP-TaxiService** [comment]
Hi, thanks for confirming my suspicion. Both SAS and RCS icons are disabled deliberately on remote control probes for RT's signal delay mechanism. The icons are not moddable and we are unable to catch player inputs in order to delay. We disable them so that you would be forced to press  keys "R" for RCS action and "T" for SAS action and we can capture your keystrokes and add time delay to them.

Until Private Division add the moddability to the icons, we are stuck with this workaround and waiting for this eventual change.
