### ISSUE TITLE
Read settings from GameDatabase

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#96]
Loading mod settings with KSP's built-in mechanism rather than manually will allow ModuleManager users to tweak settings for specific mods.

**Comment by Peppie23** [comment]
Merged to v1.6.

Can one RSS/RO player test this new function?
DLL: https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/build-1.6.0-182
New RSSConfig: https://gist.github.com/Peppie23/b7d6bc935a1b499c738c

It's now possible to override all values except the Mapfilter and the ActiveVesselGuid. I ignore these values on third party configs.

**Comment by pjf** [comment]
> +1 for this. I'm even willing to pony up $5 USD (or equivalent in BTC or DOGE) to whomever makes this change. :)

@Peppie23 : Thank you so much! I believe I now owe you, or the organisation of your choice, $5. If you happen to have bitcoin/dogecoin/paypal details handy, I'll make sure that happens! (You can also email them to paul.j.fenwick@gmail.com if you don't want them appearing in a comment.)

**Comment by Peppie23** [comment]
@pjf thanks but i only could make this so quickly by using Starstriders code. He deserves it ;-)

**Comment by Sigma88** [comment]
hi guys, sorry to dig up an old issue but I didn't feel like opening a new one since this was already discussed here.

I tried to change the **Range Multiplier** parameter using a MM config and it didn't work.
I'm not sure if the settings.cfg was ever set to use MM syntax tho.
could any of you enlighten me on this? :) thanks

btw, I've checked the MM cache file and it shows the rangemultiplier I want, but ingame all the probes act like the rangemultiplier is still = 1

**Comment by NathanKell** [comment]
@Felbourn and I dug here and, well, it's not what you expect. RT loads settings by finding all nodes and then loading them one by one; you create a fresh RemoteTech_Settings node rather than MM-patching the existing node.
Well, you could MM patch the subsequent nodes, but you need to be patching the node(s) that are not the one loaded from the RT folder.

Check out how RO and RSS do this.
